### ISSUE TITLE
Example setup for connection to ss ?

### ISSUE THREAD

**Issue by Docop2** [kokrange/ss-openwrt-transparent-proxy-router#1]
Hi  So i.ve tried with the official shadowsock package for owrt and see yours. While it look nice, do you have an example of a working setup ? I do have a server, i can connect with pretty much all , but openwrt, i have no clue how to config it .. or just put the server in sss0 and do a sstun or ssredir.. ? I know it might be for a futur wiki.. but perhaps.
thanks in advance.

**Comment by kokrange** [comment]
Follow the steps  described in README to config your openwrt and vpn servers. It may require a little bit knowledge of linux shell command, ssh and docker.
